DROP DATABASE IF EXISTS dbName;

CREATE DATABASE dbName;

USE dbName;

CREATE TABLE users (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(100) NOT NULL UNIQUE,
  `name` VARCHAR(50) NOT NULL,
  `pic` VARCHAR(255) NULL,
  `bio` VARCHAR(255) NULL
);

CREATE TABLE items (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `proposer_id` INT NOT NULL,
  FOREIGN KEY (`proposer_id`) REFERENCES users (`id`)
);